# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

prod_csr_dense <- function(csr, dense_m_r) {
    .Call(`_MatrixCSR_prod_csr_dense`, csr, dense_m_r)
}

prod_dense_csr <- function(dense_m_r, csr_r) {
    .Call(`_MatrixCSR_prod_dense_csr`, dense_m_r, csr_r)
}

tcrossprod_dense_csr <- function(dense_m_r, csr_r) {
    .Call(`_MatrixCSR_tcrossprod_dense_csr`, dense_m_r, csr_r)
}

crossprod_csr_dense <- function(csr_r, dense_m_r) {
    .Call(`_MatrixCSR_crossprod_csr_dense`, csr_r, dense_m_r)
}

